[package]
name = "asknothingx2-eventsub"
version = "0.0.3"
authors = ["m3id"]
edition = "2021"
description = "Twitch eventsub"
repository = "https://github.com/m3idnotfree/asknothingx2"
license = "MIT OR Apache-2.0"
keywords = ["twitch"]

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
