use asknothingx2_util::api::content_type::Application;

define_tests!(Application);

prop_compose! {
    fn base_stragety()(
        s in prop_oneof![
            Just(Application::Json),
            Just(Application::Xml),
            Just(Application::Pdf),
            Just(Application::Zip),
            Just(Application::Gzip),
            Just(Application::OctetStream),
            Just(Application::FormUrlEncoded),
            Just(Application::Postscript),
            Just(Application::Rtf),
            Just(Application::Yaml),
            Just(Application::Wasm),
            Just(Application::AtomXml),
            Just(Application::RssXml),
            Just(Application::SoapXml),
            Just(Application::XhtmlXml),
            Just(Application::XsltXml),
            Just(Application::MsWord),
            Just(Application::MsExcel),
            Just(Application::MsPowerpoint),
            Just(Application::MsProject),
            Just(Application::MsWorks),
            Just(Application::MsVisio),
            Just(Application::MsOneNote),
            Just(Application::VndOpenXmlWordDoc),
            Just(Application::VndOpenXmlWordTemplate),
            Just(Application::VndOpenXmlSpreadsheet),
            Just(Application::VndOpenXmlSpreadsheetTemplate),
            Just(Application::VndOpenXmlPresentation),
            Just(Application::VndOpenXmlPresentationTemplate),
            Just(Application::VndOasisText),
            Just(Application::VndOasisSpreadsheet),
            Just(Application::VndOasisPresentation),
            Just(Application::VndOasisGraphics),
            Just(Application::VndOasisFormula),
            Just(Application::VndOasisDatabase),
            Just(Application::X7zCompressed),
            Just(Application::XRarCompressed),
            Just(Application::XTar),
            Just(Application::XBzip2),
            Just(Application::XAceCompressed),
            Just(Application::XStuffit),
            Just(Application::VndDebian),
            Just(Application::VndRar),
            Just(Application::JavaArchive),
            Just(Application::JavaSerializedObject),
            Just(Application::JavaVm),
            Just(Application::XShellScript),
            Just(Application::XPerl),
            Just(Application::XTcl),
            Just(Application::XPython),
            Just(Application::XRuby),
            Just(Application::EpubZip),
            Just(Application::VndAmazonEbook),
            Just(Application::XMobipocketEbook),
            Just(Application::VndMsHtmlhelp),
            Just(Application::VndSqlite3),
            Just(Application::XNetcdf),
            Just(Application::XHdf),
            Just(Application::VndMbox),
            Just(Application::VndAdobeAir),
            Just(Application::VndAdobeXdp),
            Just(Application::VndAdobeXfdf),
            Just(Application::VndAdobePhotoshop),
            Just(Application::VndGoogleEarthKml),
            Just(Application::VndGoogleEarthKmz),
            Just(Application::VndAppleInstaller),
            Just(Application::VndAndroidPackage),
            Just(Application::VndAutocadDwg),
            Just(Application::VndAutocadDxf),
    ]) -> Application { s }
}
