use asknothingx2_util::api::content_type::Image;

define_tests!(Image);

prop_compose! {
    pub fn base_stragety()(
        s in prop_oneof![
            Just(Image::Apng),
            Just(Image::Jpeg),
            Just(Image::Png),
            Just(Image::Gif),
            Just(Image::Webp),
            Just(Image::SvgXml),
            Just(Image::Tiff),
            Just(Image::Bmp),
            Just(Image::Icon),
            Just(Image::Avif),
            Just(Image::Heic),
            Just(Image::Cgm),
            Just(Image::Ief),
            Just(Image::G3fax),
            Just(Image::PrsBtif),
            Just(Image::VndDjvu),
            Just(Image::VndDwg),
            Just(Image::VndDxf),
            Just(Image::VndFastbidsheet),
            Just(Image::VndFpx),
            Just(Image::VndFst),
            Just(Image::VndNetFpx),
            Just(Image::VndWapWbmp),
            Just(Image::VndXiff),
            Just(Image::VndMsModi),
            Just(Image::XAdobeDng),
            Just(Image::XCanonCr2),
            Just(Image::XCanonCrw),
            Just(Image::XEpsonErf),
            Just(Image::XFujiRaf),
            Just(Image::XKodakDcr),
            Just(Image::XKodakK25),
            Just(Image::XKodakKdc),
            Just(Image::XMinoltaMrw),
            Just(Image::XNikonNef),
            Just(Image::XOlympusOrf),
            Just(Image::XPanasonicRaw),
            Just(Image::XPentaxPef),
            Just(Image::XSigmaX3f),
            Just(Image::XSonyArw),
            Just(Image::XSonySr2),
            Just(Image::XSonySrf),
            Just(Image::XCmuRaster),
            Just(Image::XCmx),
            Just(Image::XFreehand),
            Just(Image::XIcns),
            Just(Image::XPcx),
            Just(Image::XPict),
            Just(Image::XPortableAnymap),
            Just(Image::XPortableBitmap),
            Just(Image::XPortableGraymap),
            Just(Image::XPortablePixmap),
            Just(Image::XRgb),
            Just(Image::XXbitmap),
            Just(Image::XXpixmap),
            Just(Image::XXwindowdump),
    ]) -> Image { s }
}
